name = input("Enter Name: ")
enroll = input("Enter Enrollment Number: ")
branch = input("Enter Branch: ")
age = input("Enter Age: ")
email = input("Enter Email: ")
mobile = input("Enter Mobile Number: ")

print("===========================")
print(name)
print(enroll)
print("Branch:", branch)
print("Age:", age, "years")
print("Email:", email)
print("Mobile No:", mobile)
print("===========================")
